wandb_version: 1

basedir:
  desc: null
  value: dataset
datatype:
  desc: null
  value: pokemon
device:
  desc: null
  value: cuda:0
gpu_id:
  desc: null
  value: 0
exp_name:
  desc: null
  value: debug
img_size:
  desc: null
  value: 128
diffuse_step:
  desc: null
  value: 1000
ema_beta:
  desc: null
  value: 0.995
batch_size:
  desc: null
  value: 16
lr_init:
  desc: null
  value: 0.0001
max_warmup_step:
  desc: null
  value: 500
max_epoch:
  desc: null
  value: 50
save_epoch:
  desc: null
  value: 10
eval_epoch:
  desc: null
  value: 10
N_eval:
  desc: null
  value: 5
max_step:
  desc: null
  value: 2600
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.3
    framework: huggingface
    huggingface_version: 4.29.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684672066.011809
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 83
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 83
      3:
      - 7
      - 13
      - 16
      - 23
      4: 3.9.16
      5: 0.15.3
      6: 4.29.2
      8:
      - 5
    m:
    - 1: train/epoch
      6:
      - 3
    - 1: test/epoch
      6:
      - 3
    - 1: train/ep_loss
      5: 1
      6:
      - 1
    - 1: test/ddpm_generation._type
      5: 2
      6:
      - 1
    - 1: test/ddpm_generation.sha256
      5: 2
      6:
      - 1
    - 1: test/ddpm_generation.size
      5: 2
      6:
      - 1
    - 1: test/ddpm_generation.path
      5: 2
      6:
      - 1
    - 1: test/ddpm_generation.format
      5: 2
      6:
      - 1
    - 1: test/ddpm_generation.width
      5: 2
      6:
      - 1
    - 1: test/ddpm_generation.height
      5: 2
      6:
      - 1
